# Generated by Django 5.2.7 on 2025-10-17 21:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IletisimMesaji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.CharField(max_length=100, verbose_name='Ad Soyad')),
                ('telefon', models.CharField(max_length=15, verbose_name='Telefon')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('konu', models.CharField(choices=[('randevu', 'Randevu Talebi'), ('bilgi', 'Genel Bilgi'), ('sikayet', 'Şikayet'), ('oneri', 'Öneri'), ('diger', 'Diğer')], max_length=20, verbose_name='Konu')),
                ('mesaj', models.TextField(verbose_name='Mesaj')),
                ('durum', models.CharField(choices=[('yeni', 'Yeni'), ('okundu', 'Okundu'), ('yanıtlandı', 'Yanıtlandı'), ('kapandı', 'Kapandı')], default='yeni', max_length=20, verbose_name='Durum')),
                ('olusturma_tarihi', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Oluşturma Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('admin_notu', models.TextField(blank=True, null=True, verbose_name='Admin Notu')),
            ],
            options={
                'verbose_name': 'İletişim Mesajı',
                'verbose_name_plural': 'İletişim Mesajları',
                'ordering': ['-olusturma_tarihi'],
            },
        ),
    ]
