# Generated by Django 5.2.7 on 2025-10-18 12:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hasta_yonetim', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doktor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.CharField(max_length=150, verbose_name='Ad Soyad')),
                ('unvan', models.CharField(blank=True, max_length=100, verbose_name='Ünvan')),
                ('bolum', models.CharField(choices=[('dahiliye', 'Dahiliye'), ('goz', 'Göz Hastalıkları'), ('pediatri', 'Pediatri'), ('genel_cerrahi', 'Genel Cerrahi'), ('ortopedi', 'Ortopedi'), ('kadin_dogum', 'Kadın Doğum')], max_length=50, verbose_name='Bölüm')),
                ('bio', models.TextField(blank=True, verbose_name='Biyografi')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-Posta')),
                ('telefon', models.CharField(blank=True, max_length=25, verbose_name='Telefon')),
                ('foto', models.CharField(blank=True, max_length=255, verbose_name='Fotoğraf (dosya adı veya URL)')),
                ('sira', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('olusturma_tarihi', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Oluşturma Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
            ],
            options={
                'verbose_name': 'Doktor',
                'verbose_name_plural': 'Doktorlar',
                'ordering': ['sira', 'ad_soyad'],
            },
        ),
    ]
