# Generated by Django 5.2.7 on 2025-10-18 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hasta_yonetim', '0002_doktor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doktor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='doktor',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='doktor',
            name='telefon',
        ),
    ]
