# Generated by Django 5.2.7 on 2025-12-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hasta_yonetim', '0003_remove_doktor_email_remove_doktor_foto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doktor',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='doktor_fotograflari/', verbose_name='Fotoğraf'),
        ),
    ]
